[viv-61]Update user
huhulacolle/VivaRecruit_Back pull request #24
Opened 2023-05-16 20:17 UTC by sacha0914

2023-05-16 20:53 UTC, JulienBois requested changes
Il serait bien de changer la réponse de la requête qui est actuellement "Le job à bien été modifié"

2023-05-18 21:56 UTC, JulienBois requested changes
Il serait bien de mettre un forbidden response quand un utilisateur essaye de modifier les informations d'un autre utilisateur

2023-05-19 15:14 UTC, JulienBois requested changes
Le apiCreatedResponse et forbidden response ne doivent pas être associés à la classe mais à la méthode

2023-05-19 15:42 UTC, JulienBois requested changes
Ce serait bien de pouvoir vérifier pendant le update que l'utilisateur existe si non on renvoit une badRequestException

2023-05-20 15:03 UTC, JulienBois requested changes
Il serait bien que l'on ai pas besoin de metrre l'id du compte à changer, nous l'avons déjà dans le token

2023-05-22 13:08 UTC, JulienBois submitted a review, later dismissed

2023-05-22 13:10 UTC, JulienBois approved these changes

2023-05-22 14:11 UTC, GianniB77 approved these changes
C'est bon

2023-05-22 14:11 UTC, merged